"use client";
import { useEffect, useState } from "react";
import { ShieldCheck, Plus, Play, FileText, Database, GitBranch } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { ASSETS, SOURCES, type Evidence, scoreEvidence, makePlan } from "@/lib/engine";
type Change={id:string;asset_id:string;title:string;description:string;created:string};
type Run={id:string;created:string;result:ReturnType<typeof scoreEvidence>};
type Plan={id:string;run_id:string;created:string;document:ReturnType<typeof makePlan>};
type Detail={change:Change;runs:Run[];findings:Evidence[];plans:Plan[];audit:{id:string;action:string;created:string}[]};
async function api<T = {changes:Change[];user:string}>(path="",body?:unknown):Promise<T> {
 const response=await fetch(`/api/workspace${path}`,body?{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}:{cache:"no-store"});
 const result=await response.json() as T & {error?:string};if(!response.ok)throw new Error(result.error||"Request failed");return result;
}
const date=(value:string)=>new Date(value).toLocaleString();
export default function Home(){
 const [changes,setChanges]=useState<Change[]>([]),[selected,setSelected]=useState(""),[detail,setDetail]=useState<Detail|null>(null);
 const [error,setError]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[user,setUser]=useState("");
 const [newOpen,setNewOpen]=useState(false),[planOpen,setPlanOpen]=useState(false),[tab,setTab]=useState("findings"),[search,setSearch]=useState("");
 const [title,setTitle]=useState("Decommission SERVER17"),[description,setDescription]=useState("Assess dependencies and prepare a reversible decommission plan."),[asset,setAsset]=useState("SERVER17");
 const [owner,setOwner]=useState("Infrastructure Operations"),[window,setWindow]=useState("To be scheduled after review"),[constraints,setConstraints]=useState("");
 async function list(){const data=await api();setChanges(data.changes);setUser(data.user);return data.changes as Change[];}
 async function load(id:string){setDetail(await api<Detail>(`?changeId=${encodeURIComponent(id)}`));}
 useEffect(()=>{let active=true;api().then(data=>{if(active){setChanges(data.changes);setUser(data.user);if(data.changes[0])setSelected(data.changes[0].id);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false};},[]);
 useEffect(()=>{if(!selected)return;let active=true;api<Detail>(`?changeId=${encodeURIComponent(selected)}`).then(data=>{if(active)setDetail(data);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false};},[selected]);
 const run=detail?.runs[0],result=run?.result;
 async function act(action:"create"|"analyze"|"plan"){
 setBusy(true);setError("");try{
 if(action==="create"){const value=await api<{id:string}>("",{action,title,description,assetId:asset});await list();setSelected(value.id);setNewOpen(false);}
 if(action==="analyze"){await api("",{action,changeId:selected});await load(selected);setTab("findings");}
 if(action==="plan"&&run){await api("",{action,changeId:selected,runId:run.id,owner,window,constraints});await load(selected);setPlanOpen(false);setTab("plans");}
 }catch(e){setError(e instanceof Error?e.message:"Save failed");}finally{setBusy(false);}
 }
 return <div className="workspace-v2">
 <header className="v2-header"><div className="brand"><div className="brand-mark"><ShieldCheck/></div><b>ChangeGuard</b></div><span className="mock-chip">MOCK INTEGRATIONS · ANALYSIS ONLY</span><span>{user}</span></header>
 <div className="v2-layout"><aside className="v2-sidebar"><h2><GitBranch size={18}/> Saved changes</h2><Button onClick={()=>setNewOpen(true)} disabled={busy}><Plus size={16}/>New change</Button><div className="change-list">{changes.map(c=><button disabled={busy} aria-current={selected===c.id?"page":undefined} className={selected===c.id?"selected":""} key={c.id} onClick={()=>{setError("");setSelected(c.id);setTab("findings");}}><strong>{c.title}</strong><small>{c.asset_id} · {date(c.created)}</small></button>)}</div><p>v0.2 · Saved analysis snapshots<br/>No infrastructure execution</p></aside>
 <main className="v2-main">
 {error&&<div role="alert" className="error-banner">{error} <Button variant="outline" onClick={()=>{setError("");setLoading(true);list().then(rows=>selected?load(selected):rows[0]&&setSelected(rows[0].id)).catch(e=>setError(e.message)).finally(()=>setLoading(false));}}>Retry loading</Button> <a href="/signin-with-chatgpt?return_to=/" target="_top">Sign in</a></div>}
 {loading||(!error&&selected&&detail?.change.id!==selected)?<p role="status">Loading saved workspace…</p>:!detail||detail.change.id!==selected?<section className="panel empty-v2"><Database/><h1>Plan your first infrastructure change</h1><p>Create a request, select a mock asset, and assess its dependencies. Changes and analysis history are saved across sessions.</p><Button onClick={()=>setNewOpen(true)}>Create change request</Button></section>:<>
 <section className="page-heading"><div><div className="eyebrow">CHANGE REQUEST · {detail.change.asset_id}</div><h1>{detail.change.title}</h1><p>{detail.change.description}</p></div><div className="heading-actions"><Button disabled={busy} variant="outline" onClick={()=>act("analyze")}><Play size={16}/>{busy?"Saving…":"Run mock analysis"}</Button><Button disabled={busy||!run} onClick={()=>setPlanOpen(true)}><FileText size={16}/>Generate plan</Button></div></section>
 {!run?<section className="panel empty-v2"><h2>No analysis yet</h2><p>Run the mock collectors to save the first evidence snapshot. No risk score is assigned before evidence collection.</p></section>:<>
 <section className="v2-metrics"><article className="panel"><span>Risk score · {result!.level}</span><strong>{result!.score}<small>/100</small></strong><p>Observed dependencies: {result!.dependency}/70<br/>Uncertainty: {result!.uncertainty}/30</p></article><article className="panel"><span>Evidence coverage</span><strong>{result!.coverage}%</strong><p>{detail.findings.filter(f=>f.status==="observed").length} of {detail.findings.length} checks observed<br/>{result!.unknown} unknown checks</p></article><article className="panel"><span>Readiness</span><h2>{result!.readiness}</h2><p>{result!.recommendation}</p></article></section>
 <p className="run-meta">Mock snapshot · {date(run.created)} · Rules {result!.version} · {run.id}</p>
 </>}
 <Tabs value={tab} onValueChange={setTab}><TabsList className="v2-tabs"><TabsTrigger value="findings">Evidence</TabsTrigger><TabsTrigger value="graph">Dependencies</TabsTrigger><TabsTrigger value="plans">Plans ({detail.plans.length})</TabsTrigger><TabsTrigger value="history">History</TabsTrigger><TabsTrigger value="systems">Collectors</TabsTrigger></TabsList>
 <TabsContent value="findings"><label className="field-label">Filter evidence<Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Source, finding, or status"/></label><div className="evidence-grid">{detail.findings.filter(f=>`${f.source} ${f.title} ${f.status}`.toLowerCase().includes(search.toLowerCase())).map(f=><article className="panel evidence-card" key={f.key}><span className={`status-${f.severity}`}>{f.status==="unknown"?"UNKNOWN":f.severity.toUpperCase()} · {f.source}</span><h3>{f.title}</h3><p>{f.detail}</p><p className="points">{f.status==="unknown"?20:f.points} {f.status==="unknown"?"uncertainty":"dependency"} points before category cap</p><details><summary>Inspect source evidence</summary><pre>{JSON.stringify(f.raw,null,2)}</pre><small>Mock fixture · {run&&date(run.created)}</small></details></article>)}</div>{run&&detail.findings.filter(f=>`${f.source} ${f.title} ${f.status}`.toLowerCase().includes(search.toLowerCase())).length===0&&<p>No matching evidence.</p>}</TabsContent>
 <TabsContent value="graph"><section className="panel dependency-view"><h2>{detail.change.asset_id} dependency relationships</h2><p>Relationships are limited to this mock evidence snapshot. Unknowns are not absent dependencies.</p>{detail.findings.map(f=><div key={f.key}><strong>{detail.change.asset_id}</strong><span>→ {f.status==="unknown"?"unverified":"observed"} →</span><div><strong>{f.title}</strong><p>{f.source} · {f.severity}</p></div></div>)}</section></TabsContent>
 <TabsContent value="plans">{detail.plans.length===0?<p>No plans yet. Analyze this change, then generate a draft.</p>:detail.plans.map(p=><article className="panel plan-document" key={p.id}><h2>Change plan · {p.document.assetId}</h2><p>{p.document.state} · {date(p.created)}</p><p><b>Owner:</b> {p.document.owner}<br/><b>Window:</b> {p.document.window}<br/><b>Constraints:</b> {p.document.constraints||"None supplied"}</p><p className="run-meta">Based on run {p.run_id}{p.run_id!==run?.id?" · Historical snapshot; review newer evidence before use":""}</p><ol>{p.document.steps.map((s,i)=><li key={i}><strong>{s.phase}</strong><p>{s.action}</p><p><b>Checkpoint:</b> {s.validation}</p></li>)}</ol></article>)}</TabsContent>
 <TabsContent value="history"><section className="panel history-v2"><h2>Analysis snapshots</h2>{detail.runs.map(r=><details key={r.id}><summary>{date(r.created)} · {r.result.score}/100 · {r.result.readiness}</summary><p>Run {r.id} · {r.result.version}</p><pre>{JSON.stringify(r.result.contributions,null,2)}</pre></details>)}<h2>Audit history</h2>{detail.audit.map(a=><p key={a.id}><time>{date(a.created)}</time> — {a.action}</p>)}</section></TabsContent>
 <TabsContent value="systems"><section className="panel history-v2"><h2>Mock collectors</h2><p>These adapters return sample fixtures. No live systems are connected.</p>{SOURCES.map(s=><p key={s}><b>{s}</b> · {run?detail.findings.find(f=>f.source===s)?.status||"unknown":"Not collected"}</p>)}</section></TabsContent>
 </Tabs></>}
 </main></div>
 <Dialog open={newOpen} onOpenChange={v=>!busy&&setNewOpen(v)}><DialogContent className="dark-dialog"><DialogHeader><DialogTitle>New change request</DialogTitle><DialogDescription>Describe a decommission change and select its target. This version supports mock decommission analysis.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();act("create");}} className="v2-form"><label>Title<Input required minLength={3} maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Target asset<Select value={asset} onValueChange={setAsset}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{ASSETS.map(a=><SelectItem key={a.id} value={a.id}>{a.name} — {a.detail}</SelectItem>)}</SelectContent></Select></label><label>Change description<Textarea required minLength={3} maxLength={4000} value={description} onChange={e=>setDescription(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<Button disabled={busy} type="submit">{busy?"Saving…":"Save request"}</Button></form></DialogContent></Dialog>
 <Dialog open={planOpen} onOpenChange={v=>!busy&&setPlanOpen(v)}><DialogContent className="dark-dialog"><DialogHeader><DialogTitle>Generate draft plan</DialogTitle><DialogDescription>A deterministic plan based on the selected analysis, including unresolved evidence, validation and rollback. No AI model or execution is involved.</DialogDescription></DialogHeader><form className="v2-form" onSubmit={e=>{e.preventDefault();act("plan");}}><label>Owner<Input required maxLength={160} value={owner} onChange={e=>setOwner(e.target.value)}/></label><label>Proposed window<Input required maxLength={160} value={window} onChange={e=>setWindow(e.target.value)}/></label><label>Constraints<Textarea maxLength={4000} value={constraints} onChange={e=>setConstraints(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<Button disabled={busy} type="submit">{busy?"Saving…":"Generate and save draft"}</Button></form></DialogContent></Dialog>
 </div>;
}
