'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import type {Finding,Policy} from './policies';
type Scan={id:string;started:string;completed:string|null;status:string;message:string|null;policy_count:number|null;change_count:number|null;actor:string;error_code:string|null};
type History={tenant:string;scans:Scan[];baseline:{id:string;completed:string}|null};
type Detail=Scan&{policies:Policy[]|null;findings:Finding[]|null;baseline_id:string|null};
async function read<T>(path='',post=false):Promise<T>{
  const response=await fetch('/api/entra'+path,post?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'scan'})}:{cache:'no-store'});
  if(!response.headers.get('content-type')?.includes('application/json'))throw new Error('Your session may have expired. Sign in again.');
  const data=await response.json() as T & {error?:string};if(!response.ok)throw new Error(data.error??'Request failed.');return data;
}
export default function EntraMonitor(){
 const [data,setData]=useState<History|null>(null),[detail,setDetail]=useState<Detail|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 async function refresh(){const h=await read<History>();setData(h);if(h.scans[0])setDetail(await read<Detail>('?scanId='+h.scans[0].id));}
 useEffect(()=>{let active=true;read<History>().then(async h=>{if(!active)return;setData(h);if(h.scans[0]){const d=await read<Detail>('?scanId='+h.scans[0].id);if(active)setDetail(d);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false};},[]);
 async function run(){setBusy(true);setError('');try{await read('',true);}catch(e){setError(e instanceof Error?e.message:'Scan failed.');}finally{try{await refresh();}catch{setError('Could not refresh history. Reload before retrying.');}setBusy(false);}}
 return <div className="workspace-v2"><header className="v2-header"><b>ChangeGuard · Entra monitoring</b><Link href="/">Change workspace</Link></header><main className="v2-main" style={{maxWidth:1200,margin:'auto'}}>
 <section className="page-heading"><div><h1>Conditional Access monitoring</h1><p>Read-only Microsoft Entra configuration · Manual scans</p></div><button className="monitor-button" disabled={busy||loading||!data} onClick={run}>{busy?'Collecting policies…':data?.baseline?'Scan for changes':'Connect and capture baseline'}</button></section>
 {error&&<section role="alert" className="error-banner">{error} <a href="/.auth/login/aad?post_login_redirect_uri=%2Fentra">Sign in again</a></section>}
 {loading&&<p role="status">Loading monitoring history…</p>}
 {data&&<><section className="panel" style={{padding:20,marginBottom:20}}><h2>{data.baseline?'Baseline recorded':'Connect your tenant'}</h2><p>Tenant: <code style={{overflowWrap:'anywhere'}}>{data.tenant}</code></p>{!data.baseline&&<p>Grant this App Service’s managed identity the Microsoft Graph application permission <b>Policy.Read.All</b>, then capture the first baseline. Contact your tenant administrator if access is denied.</p>}<p>The first successful scan establishes a baseline. Later scans compare against the previous successful snapshot; the original baseline remains available in history. Failed scans never replace successful snapshots.</p><p>No automatic polling or remediation is enabled. Group membership, affected-user counts, named-location definitions, and changes between scans are outside this release.</p></section>
 <section className="panel" style={{padding:20,marginBottom:20}}><h2>Scan history</h2>{!data.scans.length?<p>No scans yet. An empty history is not evidence that your tenant has no policies.</p>:<div style={{overflowX:'auto'}}><table style={{width:'100%',textAlign:'left'}}><thead><tr><th>Started</th><th>Status</th><th>Policies</th><th>Changes</th><th>Details</th></tr></thead><tbody>{data.scans.map(s=><tr key={s.id}><td>{new Date(s.started).toLocaleString()}</td><td>{s.status}</td><td>{s.policy_count??'—'}</td><td>{s.change_count??'—'}</td><td><button className="monitor-button" disabled={busy} onClick={async()=>{setBusy(true);try{setDetail(await read<Detail>('?scanId='+s.id));}catch(e){setError(e instanceof Error?e.message:'Read failed.');}finally{setBusy(false);}}}>View</button></td></tr>)}</tbody></table></div>}<button className="monitor-button" disabled={busy} onClick={async()=>{setBusy(true);try{await refresh();setError('');}catch{setError('Could not refresh history.');}finally{setBusy(false);}}}>Refresh history</button></section>
 {detail&&<section><h2>Scan · {new Date(detail.started).toLocaleString()}</h2><p>{detail.message}</p><p>Started by <code style={{overflowWrap:'anywhere'}}>{detail.actor}</code></p>{detail.status==='succeeded'&&<><p>{detail.policies?.length} policies collected · {detail.findings?.length} detected changes</p>{detail.findings?.map(f=><article className="panel" style={{padding:20,marginBottom:20}} key={f.policyId}><strong>{f.severity.toUpperCase()} · {f.kind}</strong><h3>{f.name}</h3>{f.reasons.map((r,i)=><p key={i}>{r}</p>)}<p>Recommended action: validate against an approved change request and review effective access before making any correction.</p>{f.differences.map(d=><div key={d.path}><h4 style={{overflowWrap:'anywhere'}}>{d.path}</h4><div className="monitor-diff"><div><b>Before</b><pre>{JSON.stringify(d.before,null,2)}</pre></div><div><b>After</b><pre>{JSON.stringify(d.after,null,2)}</pre></div></div></div>)}<details><summary>Full policy snapshots</summary><pre>{JSON.stringify({before:f.before,after:f.after},null,2)}</pre></details></article>)}<details className="panel" style={{padding:20}}><summary>Collected policy baseline / snapshot</summary><pre>{JSON.stringify(detail.policies,null,2)}</pre></details></>}</section>}
 </>}
 </main><style>{`.monitor-button{background:#163b46;color:#e8ffff;border:1px solid #377f8d;border-radius:6px;padding:9px 14px;cursor:pointer;margin:5px}.monitor-button:disabled{opacity:.5;cursor:wait}.monitor-diff{display:grid;grid-template-columns:1fr 1fr;gap:12px}.workspace-v2 pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:400px;overflow:auto}.monitor-diff>div{min-width:0;background:#101b29;padding:12px}th,td{padding:10px}@media(max-width:640px){.monitor-diff{grid-template-columns:1fr}.v2-header{flex-wrap:wrap}}`}</style></div>;
}
